# Generated by Django 5.0.6 on 2024-07-06 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('meta_title', models.CharField(max_length=555, null=True)),
                ('meta_description', models.CharField(max_length=555, null=True)),
                ('meta_keywords', models.CharField(max_length=555, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=555, null=True)),
                ('meta_keywords', models.CharField(max_length=555, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
