# Generated by Django 5.0.6 on 2024-08-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitemapmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteMapModel',
        ),
    ]
