# Generated by Django 5.0.6 on 2024-08-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_sitemapmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text="Enter the name of the page (e.g., 'home', 'about').", max_length=200, unique=True)),
                ('title', models.CharField(help_text='Enter the title for the page.', max_length=200)),
                ('description', models.TextField(help_text='Enter the description for the page.')),
                ('keywords', models.CharField(help_text='Enter the keywords for the page (comma-separated).', max_length=200)),
            ],
        ),
    ]
